filter:
    paths: {  }
    excluded_paths: {  }
before_commands:
    - 'composer install --prefer-source'
after_commands: {  }
artifacts: {  }
tools:
    php_cs_fixer:
        extensions:
            - php
        command: php-cs-fixer
        enabled: true
        filter:
            paths:
                - 'app/src/*'
             excluded_paths:
                - '*/vendor/*'
        config:
            level: all
            fixers:
                indentation: false
                linefeed: false
                trailing_spaces: false
                unused_use: false
                phpdoc_params: false
                visibility: false
                return: false
                short_tag: false
                braces: false
                include: false
                php_closing_tag: false
                extra_empty_lines: false
                controls_spaces: false
                elseif: false
                eof_ending: false
        path_configs: {  }
    php_code_coverage:
        test_command: phpunit
        config_path: null
        enabled: true
        only_changesets: false
        filter:
            excluded_paths:
                - '*/vendor/*'
 
  
  