# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
env: 
  global: 
  - secure: 5f4e641bdf0be648f03d04d7373947719b19a786
  - GH_OWNER: alefebvre
  - GH_PROJECT_NAME: myrepositories

language: php

php:     
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev

 

script: phpunit UnitTest.php

after_script:
  - export POST_BUILD=true
  - wget http://pear.phpunit.de/get/phploc.phar
  - php phploc.phar src/ > build/result/phploc.txt
  - wget https://github.com/downloads/apigen/apigen/ApiGen-2.8.0-standalone.zip --no-check-certificate
  - unzip ApiGen-2.8.0-standalone.zip
  - rm ApiGen-2.8.0-standalone.zip
  - php apigen/apigen.php --source Application --destination build/result/docs/ 
  - bash push_to_gh_pages.sh